swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions Module
      summary: Get Transactions
      description: Retrieve all transactions for the current month
      parameters:
        - in: query
          name:
          description: Month (numeric value) for filtering transactions
          required: false
          type: integer
        - in: query
          name: year
          description: Year (numeric value) for filtering transactions
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionListResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      tags:
        - Transactions Module
      summary: Create Transaction
      description: Create a new transaction
      parameters:
        - in: body
          name: body
          description: Transaction payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction created successfully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get Transaction by ID
      description: Retrieve details of a transaction by its ID
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions Module
      summary: Update Transaction
      description: Update details of a transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
        '404':
          description: Transaction not found
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
definitions:
  Transaction:
    properties:
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: string
      balance:
        type: string
      type:
        type: string
      category:
        type: string
      notes:
        type: string
  TransactionListResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  TransactionResponse:
    type: object
    properties:
      transaction:
        $ref: '#/definitions/Transaction'
